# Generated by Django 5.0.1 on 2024-12-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='funpic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pics', models.ImageField(upload_to='memories/')),
            ],
        ),
        migrations.RenameModel(
            old_name='songs',
            new_name='song',
        ),
        migrations.DeleteModel(
            name='funpics',
        ),
    ]
