# Generated by Django 5.0.1 on 2024-12-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_funpic_rename_songs_song_delete_funpics'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funpic',
            old_name='pics',
            new_name='pic',
        ),
    ]
