# Generated by Django 5.0.1 on 2024-12-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_song_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='funpic',
            name='name',
            field=models.CharField(default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
